version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq/var/lib:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./rabbitmq/.env
